services:
  api:
    build:
      context: .
      dockerfile: src/Api/Dockerfile
    container_name: net9_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings:DefaultConnection=Host=db;Port=5432;Database=productdb;Username=user;Password=password"
    depends_on:
      db:
        condition: service_healthy
    # ESTA SEÇÃO É FUNDAMENTAL:
    networks:
      - app-network

  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=productdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d productdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge